### ISSUE TITLE
 Carthage installation - UserX.json - invalid JSON error

### ISSUE THREAD

**Issue by kreshikhin** [UserXMetrica/UserX#5]
I made Cartfile based on the instruction from README:

```
binary "https://raw.githubusercontent.com/UserXMetrica/UserX/master/UserX.json"
```

Due to the latest update of UserX, I began to receive errors while installation ` carthage update --platform ios`:

> *** Downloading binary-only framework UserX at "https://raw.githubusercontent.com/UserXMetrica/UserX/master/UserX.json"
> Unable to parse binary-only framework JSON at https://raw.githubusercontent.com/UserXMetrica/UserX/master/UserX.json due to error: invalid JSON: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around line 3, column 11." UserInfo={NSDebugDescription=Invalid value around line 3, column 11., NSJSONSerializationErrorIndex=107})))

Carthage 0.38.0
Xcode 13.1
MacOS Monterey 12.0.1

**Comment by kreshikhin** [comment]
PS. Using of prev commit from master fixes this issue:
```
binary "https://raw.githubusercontent.com/UserXMetrica/UserX/c7204239f2abcd0616854378c40b1c26404793c2/UserX.json"
```

**Comment by kreshikhin** [comment]
This problem is still well reproducible. 😡😡😡

UserX.json still have a wrong space character in the line 3, column 11.
It can be checked by looking inside of HEX representation of UserX.json

Just do "wget https://raw.githubusercontent.com/UserXMetrica/UserX/master/UserX.json" and "xxd UserX.json"

```
00000000: 7b0a 2020 2022 322e 302e 3122 3a20 2268  {.   "2.0.1": "h
...
00000060: 2020 2022 322e 302e 3422 3ac2 a022 6874     "2.0.4":.."ht
```

As we can see in line 00000000 we have three spaces 2020 20, quote 22, version 32 2e 30 2e 31, quote 22, colon 3a and again space 20.
In line 00000060 we have three three spaces 2020 20, quote 22, version 32 2e 30 2e 34, quote 22, colon 3a and C2 A0, not 20 as in first line.

C2 A0 is utf8 symbol NO-BREAK SPACE, not ASCII space 20.

So we have fail in Carthage due to of this non-ascii space symbol.

PLEASE REPLACE THIS SYMBOL WITH CORRECT ASCII space 20.

```
denis@studio Desktop % wget https://raw.githubusercontent.com/UserXMetrica/UserX/master/UserX.json
--2022-11-12 22:55:40--  https://raw.githubusercontent.com/UserXMetrica/UserX/master/UserX.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 192 [text/plain]
Saving to: ‘UserX.json’

UserX.json                         100%[==============================================================>]     192  --.-KB/s    in 0s      

2022-11-12 22:55:40 (9,64 MB/s) - ‘UserX.json’ saved [192/192]
```

```
denis@studio Desktop % xxd UserX.json 
00000000: 7b0a 2020 2022 322e 302e 3122 3a20 2268  {.   "2.0.1": "h
00000010: 7474 7073 3a2f 2f67 6974 6875 622e 636f  ttps://github.co
00000020: 6d2f 5573 6572 584d 6574 7269 6361 2f55  m/UserXMetrica/U
00000030: 7365 7258 2f72 656c 6561 7365 732f 646f  serX/releases/do
00000040: 776e 6c6f 6164 2f32 2e30 2e31 2f55 7365  wnload/2.0.1/Use
00000050: 7258 4b69 742e 4641 542e 7a69 7022 2c0a  rXKit.FAT.zip",.
00000060: 2020 2022 322e 302e 3422 3ac2 a022 6874     "2.0.4":.."ht
00000070: 7470 733a 2f2f 6769 7468 7562 2e63 6f6d  tps://github.com
00000080: 2f55 7365 7258 4d65 7472 6963 612f 5573  /UserXMetrica/Us
00000090: 6572 582f 7265 6c65 6173 6573 2f64 6f77  erX/releases/dow
000000a0: 6e6c 6f61 642f 322e 302e 342f 5573 6572  nload/2.0.4/User
000000b0: 584b 6974 2e46 4154 2e7a 6970 220a 7d0a  XKit.FAT.zip".}.
```

**Comment by UserXMetrica** [comment]
Check the latest version 2.0.5 please.
